# Generated by Django 2.1.7 on 2019-04-09 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='all_assigned_Professors',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='all_class_related',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='all_duration',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='all_end',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='all_location',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='all_makeup',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='all_others',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='all_start',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='all_title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='all_type',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='assigned_Professors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='others', to='users.Module'),
        ),
        migrations.AddField(
            model_name='class',
            name='class_related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_related', to='users.Module'),
        ),
        migrations.AddField(
            model_name='class',
            name='class_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_type', to='users.Module'),
        ),
        migrations.AddField(
            model_name='class',
            name='duration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duration', to='users.Module'),
        ),
        migrations.AddField(
            model_name='class',
            name='end',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end', to='users.Module'),
        ),
        migrations.AddField(
            model_name='class',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='users.Module'),
        ),
        migrations.AddField(
            model_name='class',
            name='makeup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_Professors', to='users.Module'),
        ),
        migrations.AddField(
            model_name='class',
            name='others',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='makeup', to='users.Module'),
        ),
        migrations.AddField(
            model_name='class',
            name='start',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start', to='users.Module'),
        ),
        migrations.AddField(
            model_name='class',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title', to='users.Module'),
        ),
    ]
