# Generated by Django 2.2 on 2019-04-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='assigned_classes',
            field=models.CharField(default='', max_length=200),
        ),
    ]
