# Generated by Django 2.1.7 on 2019-04-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='labs_per_week2',
            field=models.CharField(default='', max_length=200),
        ),
    ]
