# Generated by Django 2.1.7 on 2019-04-10 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_module_labs_per_week2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='labs_per_week2',
        ),
    ]
