# Generated by Django 2.1.7 on 2019-04-23 12:22

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=200)),
                ('persons_in_charge', models.CharField(max_length=200)),
                ('event_name', models.CharField(max_length=200)),
                ('relevant_pillars', multiselectfield.db.fields.MultiSelectField(choices=[('asd', 'ASD'), ('epd', 'EPD'), ('esd', 'ESD'), ('istd', 'ISTD'), ('hass', 'HASS')], max_length=21)),
                ('date', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
                ('num_people', models.CharField(max_length=200)),
                ('start_time', models.CharField(max_length=200)),
                ('end_time', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EventRequestResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persons_in_charge', models.CharField(max_length=200)),
                ('event_name', models.CharField(max_length=200)),
                ('relevant_pillars', multiselectfield.db.fields.MultiSelectField(choices=[('asd', 'ASD'), ('epd', 'EPD'), ('esd', 'ESD'), ('istd', 'ISTD'), ('hass', 'HASS')], max_length=21)),
                ('date', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
                ('num_people', models.CharField(max_length=200)),
                ('start_time', models.CharField(max_length=200)),
                ('end_time', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('event_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='formstoadmin.EventRequest')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('course_name', models.CharField(max_length=200)),
                ('class_related', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
                ('lesson_type', models.CharField(max_length=200)),
                ('preferred_timings', multiselectfield.db.fields.MultiSelectField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon')], max_length=17)),
                ('reasons', models.CharField(max_length=200)),
                ('remarks', models.CharField(max_length=200)),
                ('approved', models.BooleanField(null=True)),
            ],
        ),
    ]
