# Generated by Django 2.1.7 on 2019-03-22 09:05

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('course_code', models.CharField(max_length=200)),
                ('class_related', models.CharField(max_length=200)),
                ('preferred_timings', multiselectfield.db.fields.MultiSelectField(choices=[('morning', 'Morning'), ('earlyAfternoon', 'Early Afternoon'), ('lateAfternoon', 'Late Afternoon')], max_length=36)),
                ('reasons', models.CharField(max_length=200)),
                ('remarks', models.CharField(max_length=200)),
            ],
        ),
    ]
