# Generated by Django 2.2 on 2019-04-24 21:05

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('formstoadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrequest',
            name='submitted_by',
            field=models.CharField(default='huanan', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventrequestresponse',
            name='chosen',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='eventrequestresponse',
            name='submitted_by',
            field=models.CharField(default='huanan', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventrequest',
            name='relevant_pillars',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ASD', 'ASD'), ('EPD', 'EPD'), ('ESD', 'ESD'), ('ISTD', 'ISTD'), ('HASS', 'HASS')], max_length=21),
        ),
        migrations.AlterField(
            model_name='eventrequestresponse',
            name='relevant_pillars',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ASD', 'ASD'), ('EPD', 'EPD'), ('ESD', 'ESD'), ('ISTD', 'ISTD'), ('HASS', 'HASS')], max_length=21),
        ),
    ]
