# Generated by Django 2.2 on 2019-04-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formstoadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrequest',
            name='submitted_by',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='eventrequestresponse',
            name='submitted_by',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='eventrequest',
            name='date',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='eventrequest',
            name='duration',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='eventrequest',
            name='end_time',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='eventrequest',
            name='event_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='eventrequest',
            name='event_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='eventrequest',
            name='location',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='eventrequest',
            name='num_people',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='eventrequest',
            name='persons_in_charge',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='eventrequest',
            name='start_time',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='eventrequestresponse',
            name='date',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='eventrequestresponse',
            name='duration',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='eventrequestresponse',
            name='end_time',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='eventrequestresponse',
            name='event_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='eventrequestresponse',
            name='location',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='eventrequestresponse',
            name='num_people',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='eventrequestresponse',
            name='persons_in_charge',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='eventrequestresponse',
            name='start_time',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='schedulerequest',
            name='class_related',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='schedulerequest',
            name='course_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='schedulerequest',
            name='duration',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='schedulerequest',
            name='lesson_type',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='schedulerequest',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='schedulerequest',
            name='reasons',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='schedulerequest',
            name='remarks',
            field=models.CharField(default='', max_length=200),
        ),
    ]
