# Generated by Django 2.2 on 2019-04-23 06:41

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('formstoadmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedulerequest',
            old_name='course_code',
            new_name='course_name',
        ),
        migrations.RemoveField(
            model_name='eventrequest',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='eventrequest',
            name='start_date',
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='date',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='end_time',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='start_time',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedulerequest',
            name='duration',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedulerequest',
            name='lesson_type',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedulerequest',
            name='preferred_timings',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon')], max_length=17),
        ),
    ]
