# Generated by Django 2.2 on 2019-04-24 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formstoadmin', '0002_auto_20190425_0434'),
        ('formstoadmin', '0002_auto_20190425_0505'),
    ]

    operations = [
    ]
