# Generated by Django 2.2 on 2019-04-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formstoadmin', '0002_auto_20190423_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrequest',
            name='num_people',
            field=models.CharField(default=100, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventrequest',
            name='duration',
            field=models.CharField(max_length=200),
        ),
    ]
