# Generated by Django 2.1.7 on 2019-04-14 08:03

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('formstoadmin', '0002_auto_20190322_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persons_in_charge', models.CharField(max_length=200)),
                ('event_name', models.CharField(max_length=200)),
                ('relevant_pillars', multiselectfield.db.fields.MultiSelectField(choices=[('asd', 'ASD'), ('epd', 'EPD'), ('esd', 'ESD'), ('istd', 'ISTD'), ('hass', 'HASS')], max_length=21)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('duration', models.DurationField()),
            ],
        ),
    ]
