# Generated by Django 2.2 on 2019-04-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formstoadmin', '0003_auto_20190423_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrequest',
            name='location',
            field=models.CharField(default='Singapore', max_length=200),
            preserve_default=False,
        ),
    ]
