# Generated by Django 2.2 on 2019-04-24 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formstoadmin', '0003_merge_20190425_0651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventrequestresponse',
            name='chosen',
        ),
    ]
