# Generated by Django 2.2 on 2019-04-23 09:58

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('formstoadmin', '0004_eventrequest_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrequest',
            name='event_id',
            field=models.CharField(default='001', max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='EventRequestResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persons_in_charge', models.CharField(max_length=200)),
                ('event_name', models.CharField(max_length=200)),
                ('relevant_pillars', multiselectfield.db.fields.MultiSelectField(choices=[('asd', 'ASD'), ('epd', 'EPD'), ('esd', 'ESD'), ('istd', 'ISTD'), ('hass', 'HASS')], max_length=21)),
                ('date', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
                ('num_people', models.CharField(max_length=200)),
                ('start_time', models.CharField(max_length=200)),
                ('end_time', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('event_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='formstoadmin.EventRequest')),
            ],
        ),
    ]
