# Generated by Django 2.2 on 2019-04-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formstoadmin', '0005_auto_20190423_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrequest',
            name='submitted_by',
            field=models.CharField(default='anon', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventrequestresponse',
            name='submitted_by',
            field=models.CharField(default='anon', max_length=200),
            preserve_default=False,
        ),
    ]
